---

- name: create security group with ports 22 & 80
  ec2_group:
    name: "{{vpc_prefix}}_SecGroup"
    description: ssh + http
    vpc_id: "{{vpc_data.vpc.id}}"
    region: "{{aws_region}}"
    rules:
      - proto: tcp
        ports:
        - 22
        cidr_ip: "{{my_ip}}"
      - proto: tcp
        ports:
        - 80
        cidr_ip: 0.0.0.0/0
    tags: 
      Name: "{{vpc_prefix}}_SecGroup"

- name: create EC2 instance
  ec2:
    key_name: ACIT4640
    exact_count: 1
    count_tag:
      Name: "{{ ec2_instance_name }}"
    group: "{{vpc_prefix}}_SecGroup"
    instance_type: t2.micro
    image: "{{ami_id}}"
    region: "{{aws_region}}"
    wait: yes
    vpc_subnet_id: "{{subnet_data.subnet.id}}"
    volumes:
      - device_name: /dev/sda1
        volume_size: 8
        delete_on_termination: true
    instance_tags:
      Name: "{{ec2_instance_name}}"
  register: ec2
- debug:
    msg: "{{ec2}}"

- name: create elastic IP 
  ec2_eip:
    region: "{{aws_region}}"
    in_vpc: yes
    device_id: "{{ec2.tagged_instances[0].id}}"
    state: present
  register: eip_data
- debug:
    msg: "{{eip_data}}"


...