---

    - name: Install packages
      become: yes
      package:
        name: [git, wget]
        state: present

    - name: Create user todoapp
      become: yes
      user:
        name: "{{todo_user}}"
        state: present
        home: /home/{{todo_user}}

    - name : Clone app into /home/todoapp/app
      git:
        repo: https://github.com/AndiLuo/MERN-Stack-Todo-List-App.git
        dest: "{{todoapp_path}}"
        force: yes
      become: yes
      become_user: "{{todo_user}}"
    
    - name: Install packages for back end based on package.json.
      npm:
        path: "{{todoapp_path_back}}"
      become: yes
      become_user: "{{todo_user}}"
      ignore_errors: yes
    
    - name: Install packages for the front end based on package.json.
      npm:
        path: "{{todoapp_path_front}}"
      become: yes
      become_user: "{{todo_user}}"  
      ignore_errors: yes

    - name: Template out todoapp.service frontend
      become: yes
      template:
        src:  todoappFront.service.j2
        dest:  /etc/systemd/system/todoappFront.service
        mode: 0644
        owner: "{{todo_user}}"
        group: "{{todo_user}}"
      notify: restart todoapp service 

    
    - name: Template out todoapp.service backend
      become: yes
      template:
        src:  todoappBack.service.j2
        dest:  /etc/systemd/system/todoappBack.service
        mode: 0644
        owner: "{{todo_user}}"
        group: "{{todo_user}}"
      notify: restart todoapp service

    - name: Template out database.js
      become: yes
      template:
        src:  database.j2
        dest:  "{{todoapp_path_back}}/database.js"
        mode: 0664
        owner: "{{todo_user}}"
        group: "{{todo_user}}"

    - name: Make sure todoapp backend service is running
      become: yes
      systemd:
        state: started
        # enabled: yes
        # daemon_reload: yes
        name: todoappFront
      notify: register app

    - name: Make sure todoapp frontend service is running
      become: yes
      systemd:
        state: started
        # enabled: yes
        # daemon_reload: yes
        name: todoappBack
      notify: register app
...